import requests
from light import Light, Color

razer_border_works = 0
mx = 22 + 2 * razer_border_works
class RazerKeyboard(Light):
    def __init__(self, chromasdk_uri):
        self.chromasdk_uri = chromasdk_uri
        self.num_zones = mx * (6 + 2 * razer_border_works)
        self.colors = [
            [0] * 24,
            [0] * 24,
            [0] * 24,
            [0] * 24,
            [0] * 24,
            [0] * 24,
            [0] * 24,
            [0] * 24,
        ]
        self.name = "Razer Keyboard"

    def update(self):
        request = {
            "effect": "CHROMA_CUSTOM2",
            "param": {
                "color": self.colors,
                "key": [
                    [0] * 22,
                    [0] * 22,
                    [0] * 22,
                    [0] * 22,
                    [0] * 22,
                    [0] * 22,
                ]
            }
        }
        requests.put(
            "{}/keyboard".format(self.chromasdk_uri), verify=False, json=request)

    def set_color(self, color: Color, zone: int):
        self.colors[(zone // mx) + 1 - razer_border_works][(zone % mx) + 1 - razer_border_works] = color.toBGRInt()




zone_to_keynames = {0: 'no',
                    1: 'no',
                    2: 'no',
                    3: 'no',
                    4: 'no',
                    5: 'no',
                    6: 'no',
                    7: 'no',
                    8: 'no',
                    9: 'no',
                    10: 'no',
                    11: 'no',
                    12: 'no',
                    13: 'no',
                    14: 'no',
                    15: 'no',
                    16: 'no',
                    17: 'no',
                    18: 'no',
                    19: 'no',
                    20: 'no',
                    21: 'no',
                    22: 'no',
                    23: 'no',
                    24: 'no',
                    25: 'no',
                    26: 'esc',
                    27: 'no',
                    28: 'f1',
                    29: 'f2',
                    30: 'f3',
                    31: 'f4',
                    32: 'f5',
                    33: 'f6',
                    34: 'f7',
                    35: 'f8',
                    36: 'f9',
                    37: 'f10',
                    38: 'f11',
                    39: 'f12',
                    40: 'prtsc',
                    41: 'scrlk',
                    42: 'pause',
                    43: 'musiccontrols',
                    44: 'no',
                    45: 'no',
                    46: 'volume',
                    47: 'no',
                    48: 'no',
                    49: 'no',
                    50: 'tick',
                    51: '1',
                    52: '2',
                    53: '3',
                    54: '4',
                    55: '5',
                    56: '6',
                    57: '7',
                    58: '8',
                    59: '9',
                    60: '0',
                    61: '-',
                    62: '=',
                    63: 'backspace',
                    64: 'ins',
                    65: 'home',
                    66: 'pageup',
                    67: 'numlk',
                    68: 'nm/',
                    69: 'nm*',
                    70: 'nm-',
                    71: 'no',
                    72: 'no',
                    73: 'ni',
                    74: 'tab',
                    75: 'q',
                    76: 'w',
                    77: 'e',
                    78: 'r',
                    79: 't',
                    80: 'y',
                    81: 'u',
                    82: 'i',
                    83: 'o',
                    84: 'p',
                    85: '[',
                    86: ']',
                    87: 'no',
                    88: 'del',
                    89: 'end',
                    90: 'pagedown',
                    91: 'nm7',
                    92: 'nm8',
                    93: 'nm9',
                    94: 'nm+',
                    95: 'no',
                    96: 'no',
                    97: 'no',
                    98: 'caps',
                    99: 'a',
                    100: 's',
                    101: 'd',
                    102: 'f',
                    103: 'g',
                    104: 'h',
                    105: 'j',
                    106: 'k',
                    107: 'l',
                    108: ';',
                    109: "'",
                    110: '\\',
                    111: 'enter',
                    112: 'no',
                    113: 'no',
                    114: 'no',
                    115: 'nm4',
                    116: 'nm5',
                    117: 'nm6',
                    118: 'no',
                    119: 'no',
                    120: 'no',
                    121: 'no',
                    122: 'leftshift',
                    123: '\\',
                    124: 'z',
                    125: 'x',
                    126: 'c',
                    127: 'v',
                    128: 'b',
                    129: 'n',
                    130: 'm',
                    131: ',',
                    132: '.',
                    133: '/',
                    134: 'no',
                    135: 'rightshift',
                    136: 'no',
                    137: 'up',
                    138: 'no',
                    139: 'nm1',
                    140: 'nm2',
                    141: 'nm3',
                    142: 'nmenter',
                    143: 'no',
                    144: 'no',
                    145: 'no',
                    146: '',
                    147: '',
                    148: '',
                    149: '',
                    150: '',
                    151: '',
                    152: '',
                    153: '',
                    154: '',
                    155: '',
                    156: '',
                    157: '',
                    158: '',
                    159: '',
                    160: '',
                    161: '',
                    162: '',
                    163: '',
                    164: '',
                    165: '',
                    166: '',
                    167: '',
                    168: '',
                    169: '',
                    170: '',
                    171: '',
                    172: '',
                    173: '',
                    174: '',
                    175: '',
                    176: '',
                    177: '',
                    178: '',
                    179: '',
                    180: '',
                    181: '',
                    182: '',
                    183: '',
                    184: '',
                    185: '',
                    186: '',
                    187: '',
                    188: '',
                    189: '',
                    190: '',
                    191: ''}